# Generated by Django 5.2.5 on 2025-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillup_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COT", "COT"),
                    ("CST", "CST"),
                    ("CIT", "CIT"),
                    ("MST", "MST"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="lab_part",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C01", "C01"),
                    ("C02", "C02"),
                    ("C03", "C03"),
                    ("C04", "C04"),
                    ("CML", "CML"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
